apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: moon
  name: moon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: moon
  template:
    metadata:
      labels:
        qcloud-app: moon
    spec:
      containers:
      - env:
        image: hub.tencentyun.com/bbhj/docker
        imagePullPolicy: Always
        name: moon
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 200Mi
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey

---
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: moon
  name: moon
  namespace: default
spec:
  ports:
  - name: tcp-80-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    qcloud-app: moon
